{% set name = "cmake-build-extension" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmake-build-extension-{{ version }}.tar.gz
  sha256: 8206db07bf60ae1a51e555a15d474429c11aefd84d421324b3d723ac816fa81a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - cmake
    - gitpython
    - ninja
    - setuptools-scm

test:
  imports:
    - cmake_build_extension
  commands:
    - pip install --no-cache-dir --no-deps --no-build-isolation ./example
    - pytest ./example
  requires:
    - {{ compiler('cxx') }}
    - eigen
    - numpy
    - pip
    - pybind11
    - pytest
    - swig
  source_files:
    - example

about:
  home: https://github.com/diegoferigo/cmake-build-extension
  summary: Setuptools extension to build and package CMake projects.
  dev_url: https://github.com/diegoferigo/cmake-build-extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - diegoferigo
